name: Update JSON on Commit

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Update JSON file
      run: |
        echo "Updating JSON file..."
        node -e "const fs = require('fs');
        let json = require('./changeLog.json');
        json['lastUpdated'] = new Date().toISOString();
        fs.writeFileSync('./path/to/your-file.json', JSON.stringify(json, null, 2));"

    - name: Configure Git
      run: |
        git config --global user.name "WaiYanPhoneAant"
        git config --global user.email "wypa07@gmail.com"

    - name: Commit and push changes
      run: |
        git add ./path/to/your-file.json
        git commit -m "Update JSON file on commit to main"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
